apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/deployed-by: github-actions
resources:
  - resources/deployment.yml
  - resources/service.yml
  - resources/route.yml
patchesStrategicMerge:
- patch.yml
