apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-ts
  labels:
    app.kubernetes.io/version: ${VERSION}
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: express-ts
          image: ${IMAGE_URL}
          ports:
            - containerPort: ${APP_PORT}
          readinessProbe:
            httpGet:
              port: ${APP_PORT}
---
apiVersion: v1
kind: Service
metadata:
  name: express-ts-svc
  labels:
    app.kubernetes.io/version: ${VERSION}
spec:
  ports:
    - port: ${APP_PORT}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: express-ts
  labels:
    app.kubernetes.io/version: ${VERSION}
