# Template workflow for OpenShift GitHub Connector

name: Scan with CodeReady Dependency Analytics

on:
  - push
  - workflow_dispatch

jobs:
  crda-scan:
    name: Scan with CodeReady Dependency Analytics
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/checkout@v2

      # https://github.com/redhat-actions/openshift-tools-installer
      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: latest
          crda_key: ${{ secrets.CRDA_KEY }}

      # https://github.com/redhat-actions/crda/
      - name: CRDA Scan
        uses: redhat-actions/crda@v1
        with:
          crda_key: ${{ secrets.CRDA_KEY }}
